## 파일 확인

## 프로젝트 루트 확인

In [ ]:
from pathlib import Path

project_root = Path.cwd()

if project_root.name == "notebooks":
    project_root = project_root.parent

data_dir = project_root / "data" / "raw"

print("프로젝트 루트:", project_root)
print("데이터 폴더:", data_dir)
print("데이터 폴더 존재:", data_dir.exists())

프로젝트 루트: c:\dev\team4-shopping-dashboard
데이터 폴더: c:\dev\team4-shopping-dashboard\data\raw
데이터 폴더 존재: True

## DataSets 불러옴

In [ ]:
required_files = [
    "customers.csv",
    "products.csv",
    "orders.csv",
    "order_items.csv",
]

for file_name in required_files:

    file_path = data_dir / file_name
    print(file_name, file_path.exists(), file_path.stat().st_size if file_path.exists() else 0)

customers.csv True 51742
products.csv True 17553
orders.csv True 278533
order_items.csv True 335212

In [ ]:
import pandas as pd

print(data_dir / "customers.csv")
customers = pd.read_csv(data_dir / "customers.csv")
products = pd.read_csv(data_dir / "products.csv")
orders = pd.read_csv(data_dir / "orders.csv")
order_items = pd.read_csv(data_dir / "order_items.csv")

c:\dev\team4-shopping-dashboard\data\raw\customers.csv

In [ ]:
datasets = {

    "customers": customers,

    "products": products,

    "orders": orders,

    "order_items": order_items,

}

## 크기 요약

In [ ]:
shape_summary = pd.DataFrame(

    [

        {

            "dataset": name,

            "rows": df.shape[0],

            "columns": df.shape[1],

        }

        for name, df in datasets.items()

    ]

)

print(shape_summary)

       dataset   rows  columns
0    customers   1200        6
1     products    300        4
2       orders   6000        5
3  order_items  14603        5

## head()처음 , tail()마지막 행 확인

In [ ]:
for name, df in datasets.items():

    print(f"\n[{name}] 앞부분")

    display(df.head())

    print(f"[{name}] 뒷부분")

    display(df.tail())

[customers] 앞부분

   customer_id name gender  age city signup_date
0            1  오준수     남성   24   고양  2026-03-08
1            2  전서희     여성   27   고양  2025-03-09
2            3  권재윤     여성   45   서울  2024-08-12
3            4  송현진     여성   52   서울  2024-11-18
4            5  김준수     여성   64   서울  2024-06-24

[customers] 뒷부분

      customer_id name gender  age city signup_date
1195         1196  송은경     남성   43   창원  2024-11-19
1196         1197  전민석     남성   54   인천  2025-08-07
1197         1198  황은윤     남성   48   서울  2024-04-05
1198         1199  오민린     여성   47   서울  2026-03-09
1199         1200  박지연     여성   18   용인  2026-04-19

[products] 앞부분

   product_id         product_name category   price
0           1     프리미엄 웹캠 그레이 P001     전자기기   68000
1           2   스마트 미니 가습기 블랙 P002     생활가전  163000
2           3  컴팩트 후드 티셔츠 그레이 P003       패션   22000
3           4       프로 세럼 화이트 P004       뷰티   43000
4           5  스마트 드립백 커피 화이트 P005       식품   58000

[products] 뒷부분

     product_id        product_name category   price
295         296     플러스 에세이 블랙 P296       도서   22000
296         297   스마트 요가 매트 그린 P297      스포츠   37000
297         298    라이트 급수기 화이트 P298     반려동물   28000
298         299   에코 데스크 매트 블루 P299       문구   49000
299         300  라이트 수납 바구니 블랙 P300    홈인테리어  118000

[orders] 앞부분

   order_id  customer_id  order_date payment_method order_status
0         1         1121  2026-05-18           간편결제          배송중
1         2          993  2026-02-01           신용카드           환불
2         3          261  2025-05-08           신용카드         배송완료
3         4          783  2026-02-18           신용카드         결제완료
4         5          292  2025-06-20           신용카드         배송완료

[orders] 뒷부분

      order_id  customer_id  order_date payment_method order_status
5995      5996           98  2025-02-02           간편결제         배송완료
5996      5997         1014  2025-12-18           신용카드         배송완료
5997      5998           70  2025-01-01           간편결제         배송완료
5998      5999          507  2025-06-23           간편결제         배송완료
5999      6000          385  2025-03-11           계좌이체         배송완료

[order_items] 앞부분

   order_item_id  order_id  product_id  quantity  unit_price
0              1         1         216         4       13600
1              2         1          34         1       87000
2              3         1         187         1       93000
3              4         1         112         1      225000
4              5         2         214         1       64000

[order_items] 뒷부분

       order_item_id  order_id  product_id  quantity  unit_price
14598          14599      5999         115         2       64000
14599          14600      5999          94         1       62100
14600          14601      6000         152         2      157500
14601          14602      6000         163         1      143000
14602          14603      6000         124         2       23800

## 컬럼명 확인

In [ ]:
for name, df in datasets.items():

    print(name, df.columns.tolist())

customers ['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']
products ['product_id', 'product_name', 'category', 'price']
orders ['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']
order_items ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']

## 공백 확인

In [ ]:
for name, df in datasets.items():

    suspicious = [

        col for col in df.columns

        if col != col.strip()

    ]

    print(name, suspicious)

customers []
products []
orders []
order_items []

## info() 실행

In [ ]:


 

for name, df in datasets.items():

    print(f"\n===== {name} =====")

    df.info()

===== customers =====
<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1200 non-null   int64
 1   name         1200 non-null   str
 2   gender       1200 non-null   str
 3   age          1200 non-null   int64
 4   city         1200 non-null   str
 5   signup_date  1200 non-null   str
dtypes: int64(2), str(4)
memory usage: 56.4 KB

===== products =====
<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    300 non-null    int64
 1   product_name  300 non-null    str
 2   category      300 non-null    str
 3   price         300 non-null    int64
dtypes: int64(2), str(2)
memory usage: 9.5 KB

===== orders =====
<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        6000 non-null   int64
 1   customer_id     6000 non-null   int64
 2   order_date      6000 non-null   str
 3   payment_method  6000 non-null   str
 4   order_status    6000 non-null   str
dtypes: int64(2), str(3)
memory usage: 234.5 KB

===== order_items =====
<class 'pandas.DataFrame'>
RangeIndex: 14603 entries, 0 to 14602
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  14603 non-null  int64
 1   order_id       14603 non-null  int64
 2   product_id     14603 non-null  int64
 3   quantity       14603 non-null  int64
 4   unit_price     14603 non-null  int64
dtypes: int64(5)
memory usage: 570.6 KB

## 중복 행과 주요 키의 중복을 확인

In [ ]:

customers["customer_id"].isna().sum()

np.int64(0)

In [ ]:

customers["customer_id"].duplicated().sum()

np.int64(0)

In [ ]:
id_missing = customers["customer_id"].isna().sum()

id_duplicates = customers["customer_id"].duplicated().sum()

print("ID 결측:", id_missing)

print("ID 중복:", id_duplicates)

ID 결측: 0
ID 중복: 0

## dtype 요약

In [ ]:
dtype_rows = []

for name, df in datasets.items():

    for column, dtype in df.dtypes.items():

        dtype_rows.append(

            {

                "dataset": name,

                "column": column,

                "dtype": str(dtype),

            }

        )

dtype_summary = pd.DataFrame(dtype_rows)

dtype_summary

        dataset          column  dtype
0     customers     customer_id  int64
1     customers            name    str
2     customers          gender    str
3     customers             age  int64
4     customers            city    str
5     customers     signup_date    str
6      products      product_id  int64
7      products    product_name    str
8      products        category    str
9      products           price  int64
10       orders        order_id  int64
11       orders     customer_id  int64
12       orders      order_date    str
13       orders  payment_method    str
14       orders    order_status    str
15  order_items   order_item_id  int64
16  order_items        order_id  int64
17  order_items      product_id  int64
18  order_items        quantity  int64
19  order_items      unit_price  int64

## 결측치 개수

In [ ]:

for name, df in datasets.items():

    print(f"\n[{name}]")

    display(df.isna().sum().to_frame("missing_count"))

[customers]

             missing_count
customer_id              0
name                     0
gender                   0
age                      0
city                     0
signup_date              0

[products]

              missing_count
product_id                0
product_name              0
category                  0
price                     0

[orders]

                missing_count
order_id                    0
customer_id                 0
order_date                  0
payment_method              0
order_status                0

[order_items]

               missing_count
order_item_id              0
order_id                   0
product_id                 0
quantity                   0
unit_price                 0

## 결측치 비율

In [ ]:

missing_summaries = []

for name, df in datasets.items():

    summary = pd.DataFrame(

        {

            "missing_count": df.isna().sum(),

            "missing_rate_pct": (

                df.isna().mean() * 100

            ).round(2),

        }

    )

    summary.insert(0, "dataset", name)

    summary.insert(1, "column", summary.index)

    missing_summaries.append(summary.reset_index(drop=True))

missing_summary = pd.concat(

    missing_summaries,

    ignore_index=True

)

missing_summary

        dataset          column  missing_count  missing_rate_pct
0     customers     customer_id              0               0.0
1     customers            name              0               0.0
2     customers          gender              0               0.0
3     customers             age              0               0.0
4     customers            city              0               0.0
5     customers     signup_date              0               0.0
6      products      product_id              0               0.0
7      products    product_name              0               0.0
8      products        category              0               0.0
9      products           price              0               0.0
10       orders        order_id              0               0.0
11       orders     customer_id              0               0.0
12       orders      order_date              0               0.0
13       orders  payment_method              0               0.0
14       orders    order_status              0               0.0
15  order_items   order_item_id              0               0.0
16  order_items        order_id              0               0.0
17  order_items      product_id              0               0.0
18  order_items        quantity              0               0.0
19  order_items      unit_price              0               0.0

## 결측치 요약

In [ ]:
for name, df in df.items():
    print(f"\n--- {name} ---")
    print(df.isna().sum())

--- order_item_id ---
0

--- order_id ---
0

--- product_id ---
0

--- quantity ---
0

--- unit_price ---
0

# 날짜형 후보 확인

In [ ]:

 

date_columns = {
    "customers": ["signup_date"],
    "orders": ["order_date"],
}

for dataset_name, columns in date_columns.items():
    df = datasets[dataset_name]
    for column in columns:
        converted = pd.to_datetime(
            df[column],
            errors="coerce"
        )

        print(
            dataset_name,
            column,
            "원본 dtype:", df[column].dtype,
            "변환 실패:", converted.isna().sum()
        )

customers signup_date 원본 dtype: str 변환 실패: 0
orders order_date 원본 dtype: str 변환 실패: 0

## 날짜 범위 확인

In [ ]:

 

signup_dates = pd.to_datetime(

    customers["signup_date"],

    errors="coerce"

)

order_dates = pd.to_datetime(

    orders["order_date"],

    errors="coerce"

)

print("가입일 변환 실패:", signup_dates.isna().sum())

print("가입일 범위:", signup_dates.min(), "~", signup_dates.max())

print("주문일 변환 실패:", order_dates.isna().sum())

print("주문일 범위:", order_dates.min(), "~", order_dates.max())

가입일 변환 실패: 0
가입일 범위: 2024-01-01 00:00:00 ~ 2026-05-30 00:00:00
주문일 변환 실패: 0
주문일 범위: 2025-01-01 00:00:00 ~ 2026-07-31 00:00:00

## 날짜 컬럼을 날짜 형식으로 변환

In [ ]:
converted_date = pd.to_datetime(

    orders["order_date"],

    errors="coerce"

)

In [ ]:
converted_date = pd.to_datetime(

    orders["order_date"],

    errors="coerce"

)

In [ ]:
order_dates = pd.to_datetime(

    orders["order_date"],

    errors="coerce"

)

In [ ]:
print(order_dates.isna().sum())

print(order_dates.min())

print(order_dates.max())

0
2025-01-01 00:00:00
2026-07-31 00:00:00

## 참조하지 못한 고객 ID

In [ ]:
unknown_customer_ids = sorted(

    set(orders["customer_id"].dropna())

    - set(customers["customer_id"].dropna())

)

print("존재하지 않는 customer_id:", unknown_customer_ids)

존재하지 않는 customer_id: []

## 참조하지 못한 주문 ID

In [ ]:
unknown_order_ids = sorted(

    set(order_items["order_id"].dropna())

    - set(orders["order_id"].dropna())

)

print("존재하지 않는 order_id:", unknown_order_ids)

존재하지 않는 order_id: []

 ## 참조하지 못한 상품 ID

In [ ]:
unknown_product_ids = sorted(

    set(order_items["product_id"].dropna())

    - set(products["product_id"].dropna())

)

print("존재하지 않는 product_id:", unknown_product_ids)

존재하지 않는 product_id: []

In [ ]:
primary_keys = {

    "customers": "customer_id",

    "products": "product_id",

    "orders": "order_id",

    "order_items": "order_item_id",

}

id_check_rows = []

for name, key in primary_keys.items():

    df = datasets[name]

    id_check_rows.append(

        {

            "dataset": name,

            "key": key,

            "missing": df[key].isna().sum(),

            "duplicates": df[key].duplicated().sum(),

            "unique": df[key].nunique(),

            "rows": len(df),

        }

    )

id_check_summary = pd.DataFrame(id_check_rows)

id_check_summary

       dataset            key  missing  duplicates  unique   rows
0    customers    customer_id        0           0    1200   1200
1     products     product_id        0           0     300    300
2       orders       order_id        0           0    6000   6000
3  order_items  order_item_id        0           0   14603  14603

## 데이터 간 연결 관계 확인

In [ ]:
check1 = orders['customer_id'].isin(customers['customer_id']).all()
print("orders -> customers 연결 정상:", check1)

check2 = order_items['order_id'].isin(orders['order_id']).all()
print("order_items -> orders 연결 정상:", check2)

check3 = order_items['product_id'].isin(products['product_id']).all()
print("order_items -> products 연결 정상:", check3)

orders -> customers 연결 정상: True
order_items -> orders 연결 정상: True
order_items -> products 연결 정상: True

## 공통 데이터 로딩 함수를 작성

In [85]:
import pandas as pd

def load_all_data(data_dir='data/raw'):
    customers = pd.read_csv(f'{data_dir}/customers.csv')
    orders = pd.read_csv(f'{data_dir}/orders.csv')
    order_items = pd.read_csv(f'{data_dir}/order_items.csv')
    products = pd.read_csv(f'{data_dir}/products.csv')
    return customers, orders, order_items, products

# 사용
customers, orders, order_items, products = load_all_data()

In [86]:
customers, orders, order_items, products = load_all_data()

In [87]:
import pandas as pd
from pathlib import Path

# src/data_loader.py 기준으로 상위 폴더(프로젝트 루트)를 찾음
PROJECT_ROOT = Path('src/data_loader.py').resolve().parent.parent

def load_all_data(data_dir=None):
    if data_dir is None:
        data_dir = PROJECT_ROOT / 'data' / 'raw'
    else:
        data_dir = Path(data_dir)

    customers = pd.read_csv(data_dir / 'customers.csv')
    orders = pd.read_csv(data_dir / 'orders.csv')
    order_items = pd.read_csv(data_dir / 'order_items.csv')
    products = pd.read_csv(data_dir / 'products.csv')
    return customers, orders, order_items, products

## 반복 점검 함수

In [90]:
def inspect_dataframe(

    name: str,

    df: pd.DataFrame,

    primary_key: str | None = None,

) -> dict:

    result = {

        "dataset": name,

        "rows": df.shape[0],

        "columns": df.shape[1],

        "column_names": df.columns.tolist(),

        "dtypes": {

            column: str(dtype)

            for column, dtype in df.dtypes.items()

        },

        "missing_total": int(df.isna().sum().sum()),

        "duplicate_rows": int(df.duplicated().sum()),

    }

    if primary_key is not None:

        result["primary_key"] = primary_key

        result["key_missing"] = int(

            df[primary_key].isna().sum()

        )

        result["key_duplicates"] = int(

            df[primary_key].duplicated().sum()

        )

        result["key_unique"] = int(

            df[primary_key].nunique()

        )

    return result

In [91]:
inspection_results = []

for name, df in datasets.items():

    inspection_results.append(

        inspect_dataframe(

            name,

            df,

            primary_keys[name],

        )

    )

inspection_results

[{'dataset': 'customers',
  'rows': 1200,
  'columns': 6,
  'column_names': ['customer_id',
   'name',
   'gender',
   'age',
   'city',
   'signup_date'],
  'dtypes': {'customer_id': 'int64',
   'name': 'str',
   'gender': 'str',
   'age': 'int64',
   'city': 'str',
   'signup_date': 'str'},
  'missing_total': 0,
  'duplicate_rows': 0,
  'primary_key': 'customer_id',
  'key_missing': 0,
  'key_duplicates': 0,
  'key_unique': 1200},
 {'dataset': 'products',
  'rows': 300,
  'columns': 4,
  'column_names': ['product_id', 'product_name', 'category', 'price'],
  'dtypes': {'product_id': 'int64',
   'product_name': 'str',
   'category': 'str',
   'price': 'int64'},
  'missing_total': 0,
  'duplicate_rows': 0,
  'primary_key': 'product_id',
  'key_missing': 0,
  'key_duplicates': 0,
  'key_unique': 300},
 {'dataset': 'orders',
  'rows': 6000,
  'columns': 5,
  'column_names': ['order_id',
   'customer_id',
   'order_date',
   'payment_method',
   'order_status'],
  'dtypes': {'order_id': 'int64',
   'customer_id': 'int64',
   'order_date': 'str',
   'payment_method': 'str',
   'order_status': 'str'},
  'missing_total': 0,
  'duplicate_rows': 0,
  'primary_key': 'order_id',
  'key_missing': 0,
  'key_duplicates': 0,
  'key_unique': 6000},
 {'dataset': 'order_items',
  'rows': 14603,
  'columns': 5,
  'column_names': ['order_item_id',
   'order_id',
   'product_id',
   'quantity',
   'unit_price'],
  'dtypes': {'order_item_id': 'int64',
   'order_id': 'int64',
   'product_id': 'int64',
   'quantity': 'int64',
   'unit_price': 'int64'},
  'missing_total': 0,
  'duplicate_rows': 0,
  'primary_key': 'order_item_id',
  'key_missing': 0,
  'key_duplicates': 0,
  'key_unique': 14603}]

## LLM에 전달할 안전한 구조 요약

In [93]:
safe_schema_summary = {

    "datasets": inspection_results,

    "relationships": {

        "orders.customer_id": {

            "references": "customers.customer_id",

            "unknown_count": len(unknown_customer_ids),

        },

        "order_items.order_id": {

            "references": "orders.order_id",

            "unknown_count": len(unknown_order_ids),

        },

        "order_items.product_id": {

            "references": "products.product_id",

            "unknown_count": len(unknown_product_ids),

        },

    },

}

safe_schema_summary

{'datasets': [{'dataset': 'customers',
   'rows': 1200,
   'columns': 6,
   'column_names': ['customer_id',
    'name',
    'gender',
    'age',
    'city',
    'signup_date'],
   'dtypes': {'customer_id': 'int64',
    'name': 'str',
    'gender': 'str',
    'age': 'int64',
    'city': 'str',
    'signup_date': 'str'},
   'missing_total': 0,
   'duplicate_rows': 0,
   'primary_key': 'customer_id',
   'key_missing': 0,
   'key_duplicates': 0,
   'key_unique': 1200},
  {'dataset': 'products',
   'rows': 300,
   'columns': 4,
   'column_names': ['product_id', 'product_name', 'category', 'price'],
   'dtypes': {'product_id': 'int64',
    'product_name': 'str',
    'category': 'str',
    'price': 'int64'},
   'missing_total': 0,
   'duplicate_rows': 0,
   'primary_key': 'product_id',
   'key_missing': 0,
   'key_duplicates': 0,
   'key_unique': 300},
  {'dataset': 'orders',
   'rows': 6000,
   'columns': 5,
   'column_names': ['order_id',
    'customer_id',
    'order_date',
    'payment_method',
    'order_status'],
   'dtypes': {'order_id': 'int64',
    'customer_id': 'int64',
    'order_date': 'str',
    'payment_method': 'str',
    'order_status': 'str'},
   'missing_total': 0,
   'duplicate_rows': 0,
   'primary_key': 'order_id',
   'key_missing': 0,
   'key_duplicates': 0,
   'key_unique': 6000},
  {'dataset': 'order_items',
   'rows': 14603,
   'columns': 5,
   'column_names': ['order_item_id',
    'order_id',
    'product_id',
    'quantity',
    'unit_price'],
   'dtypes': {'order_item_id': 'int64',
    'order_id': 'int64',
    'product_id': 'int64',
    'quantity': 'int64',
    'unit_price': 'int64'},
   'missing_total': 0,
   'duplicate_rows': 0,
   'primary_key': 'order_item_id',
   'key_missing': 0,
   'key_duplicates': 0,
   'key_unique': 14603}],
 'relationships': {'orders.customer_id': {'references': 'customers.customer_id',
   'unknown_count': 0},
  'order_items.order_id': {'references': 'orders.order_id',
   'unknown_count': 0},
  'order_items.product_id': {'references': 'products.product_id',
   'unknown_count': 0}}}

# 데이터 구조 및 품질 점검 요약 LLM보고서

## 1. 데이터셋 기본 구조 및 식별자
분석 시 각 데이터가 어떤 단위를 가지며, 서로 어떻게 연결되는지 정의합니다.

| 데이터셋 | 1행(Row)의 의미 | 주요 ID (Primary Key) | 연결 고리 (Foreign Key) |
|:---|:---|:---|:---|
| **`customers`** | 쇼핑몰에 가입한 고객 1명의 고유 프로필 | `customer_id` | 해당 없음 |
| **`products`** | 쇼핑몰에서 판매 중인 독립 상품 1개 | `product_id` | 해당 없음 |
| **`orders`** | 고객이 결제를 완료한 주문(장바구니) 1건 | `order_id` | `customer_id` (`customers` 참조) |
| **`order_items`** | 주문 내역(영수증) 안의 개별 품목 1줄 | `order_item_id` | `order_id` (`orders` 참조)<br>`product_id` (`products` 참조) |

<br>

## 2. 삭제 금지 및 주의 데이터

구조 점검 요약 기준으로 `missing_total`, `duplicate_rows`, `key_duplicates`, FK `unknown_count`가 **모든 데이터셋에서 0건**으로 확인되어, 현재 시점에는 즉시 삭제를 검토해야 할 결측·중복·고아 레코드가 없습니다.

다만 향후 데이터가 갱신되거나 실제 원본을 직접 열람할 경우, 아래 유형이 발견되면 **건수와 상관없이 무작정 삭제하지 말고 원인부터 확인**해야 합니다.

| 데이터셋 | 문제 종류 | 현재 발생 건수 | 즉시 삭제하면 안 되는 이유 (위험성) |
|:---|:---|---:|:---|
| **`orders`** | 참조 불가 고객 (customers에 없는 customer_id) | 0건 | 탈퇴 회원의 과거 주문일 수 있음. 삭제 시 전체 주문·매출 통계 왜곡 |
| **`order_items`** | 참조 불가 주문 (orders에 없는 order_id) | 0건 | 시스템 지연 등으로 매칭이 꼬였을 수 있음. 삭제 시 실제 판매된 품목 소실 |
| **`order_items`** | 참조 불가 상품 (products에 없는 product_id) | 0건 | 단종되어 상품 마스터에서 제외된 항목일 수 있음. 삭제 시 과거 판매 기록 소실 |
| **`order_items`** | 주요 ID(`order_item_id`) 중복 | 0건 | 전산 오류일 수도, 동일 상품의 별도 라인 항목일 수도 있음. 확인 없이 삭제 시 매출 누락 위험 |

<br>

## 3. 추가 점검 우선순위 및 Pandas 코드 목적
요약본에는 드러나지 않지만, 실제 분석을 시작하기 전 반드시 코드로 재확인해야 할 잠재적 위험 요소입니다.

| 순위 | 점검 대상 컬럼 | 예상되는 구조적 문제 | Pandas 코드 실행 목적 (검증 방법) |
|:---:|:---|:---|:---|
| **1순위** | `signup_date`<br>`order_date` | 날짜 데이터가 문자열(`str`)로 기록되어 있어 기간 계산·정렬이 불가능함 | 문자열을 `datetime`으로 강제 변환하여, 형식이 어긋나 깨지는(NaT) 불량 데이터 색출 |
| **2순위** | `age`, `price`<br>`quantity`, `unit_price` | 정수형(`int64`)이나, 음수 나이 또는 0원 이하 가격 등 상식 밖 수치가 있을 수 있음 | 기초 통계량(최소/최대/평균)을 추출하여 현실적으로 불가능한 극단치(이상치) 감지 |
| **3순위** | 품목 없는 주문 여부 | `orders`에는 존재하나 `order_items`에 매칭 행이 하나도 없는 주문이 있을 수 있음 | `orders.order_id`가 `order_items.order_id`에 전부 존재하는지 대조하여 매출 집계 누락 여부 확인 |

```python
# [1순위] 날짜 컬럼 파싱 실패 확인
# 목적: signup_date, order_date를 datetime으로 변환했을 때 NaT(파싱 실패) 건수 확인
pd.to_datetime(customers['signup_date'], errors='coerce').isna().sum()
pd.to_datetime(orders['order_date'], errors='coerce').isna().sum()
```

```python
# [2순위] 수치 컬럼 이상치 확인
# 목적: age, price, quantity, unit_price의 최소/최대값을 확인해 음수·0 이하 등 비정상 범위 탐지
customers['age'].describe()
products['price'].describe()
order_items[['quantity', 'unit_price']].describe()
```

```python
# [3순위] 품목이 없는 주문 확인
# 목적: orders에는 있지만 order_items에 매칭되는 행이 하나도 없는 주문 건수 확인
orders.loc[~orders['order_id'].isin(order_items['order_id'])]
```